theme/resources/css/mkdocs_dhis2.css

This PR fixes the issue where tabs in the main menu had a poor contrast ratio and low readability.

fix: tab opacity

---

mkdocs.yml

docs: add links to Immunization and HIV

---

mkdocs.yml
mkdocs_single_page.yml

docs(user): use docs from dhis2/usage-analytics-app

---

mkdocs.yml

Standalone action tracker responses

Standalone action tracker responses

---

mkdocs.yml
mkdocs_single_page.yml

Updated with new structure for implementation docs, and referencing new implementation docs repo.

docs: New impl docs structure

---

mkdocs.yml

@Philip-Larsen-Donnelly , please help us getting this online today, as the packages are being published as we speak!
Thanks!

docs: Add CHIS, update links

---

mkdocs.yml

Adding the 2.37 sections.
Will re-order the sections (and remove 2.34) after the 2.37 release is complete.

chore: add 2.37

---

mkdocs_single_page_android.yml

Allow this file for those building Android documents without the need to create / modify any file locally. I will take care of any future updates if needed. Thanks :)

feat: Add mkdocs to build only Android docs

---

mkdocs.yml
mkdocs_single_page.yml

Blocked by dhis2/dhis2-docs#1088

docs(aggregate data entry): add links to docs file

---

mkdocs.yml
mkdocs_single_page.yml

- Added v1.4.0 docs config to mkdocs.yml
- Changed single page doc config for BNA to point to latest version
- Fixed a typo for scorecard app single page doc config

Feature: New version docs for BNA

---

mkdocs.yml

Matthieu: Add Intro course source doc and hierarchy under the **Training** sub category.

feat: added Intro course source doc

---

mkdocs.yml

Adding the analytics tools academy structure to the training docs

Add references for the analytics tools academy

---

mkdocs.yml

https://github.com/dhis2/dhis2-docs/pull/1174 needs to be merged in first

docs: add links to event hooks API page

---

mkdocs_preview_template.yml
preview.sh

A simpler way to preview local files

feat: preview

---

mkdocs.yml

Add in references for the tracker configuration academy

Adding in references for the tracker configuration academy in the training docs section

---

mkdocs.yml

This should be temporary until that branch is merged to master

chore: use data-quality-toolkit branch for implementation docs

---

mkdocs.yml

Adding Aggregate Data Analysis Fundamentals Source doc

Adding Aggregate Data Analysis Fundamentals Source doc

---

mkdocs.yml

- Updating sub links for navigation around Standalone action tracker v2.0 and options apps

Updates on Standalone action tracker for V2.0

---

mkdocs.yml
mkdocs_install.yml
mkdocs_single_page.yml

as these endpoints have been removed from master

chore: remove deprecated tracker docs from master DHIS2-17064

---

mkdocs.yml
mkdocs_install.yml
mkdocs_single_page.yml

Follow up to [PR-1572](https://github.com/dhis2/dhis2-docs/pull/1572) and [1576](https://github.com/dhis2/dhis2-docs/pull/1576)

docs: update v42 datastore management doc references

---

mkdocs.yml

depends on: https://github.com/dhis2/route-manager-app/pull/27 being merged to main first

docs: add link to route manager app
